### PR TITLE
Abort function for io.Copy

### PR DESCRIPTION
**Pull request by KemoKemo**
Hello @hajimehoshi !

I was moved by the method of playing music by combining [go-mp3](https://github.com/hajimehoshi/go-mp3) and oto library with io.Copy. [here](http://qiita.com/hajimehoshi/items/9f3b7186ec0b8e2850a4)
I would like to create a mechanism like jukebox using this technique and incorporate it into my game using [ebiten](https://github.com/hajimehoshi/ebiten).

So I searched for a way to interrupt music play by interrupting io.Copy and implemented.
[Here](https://gist.github.com/KemoKemo/ab3776224e7557b389ed07595546f78c) is an example of an interruption sample written based on your sample.

Would you please give me comments or advice?

### CODE REVIEW

**Comment by hajimehoshi** [comment]
Hi Kemo-kemo-san!

As far as I know, there is no feasible way to suspend copying of `io.Copy`.

Instead, how about making a 'abortable' copy function? The (pseudo) code would be:

```go
func AbortableCopy(w io.Writer, r io.Reader, abortCh <-chan struct{}) (int, error) {
  type readResult struct {
    buf []uint8
    err error
  }
  readCh := make(chan, readResult)
  go func() {
    buf := make([]uint8, 4096)
    for {
      n, err := r.Read(buf)
      r := ReadResult{buf[:n], nil}
      if err != nil && err != io.EOF {
        r.err = err
      }
      readCh <- r
      if err != nil {
        break
      }
    }
    close(readCh)
  }()
  written := 0
loop:
  for {
    select {
    case buf, ok := <-readCh:
      if !ok {
        readCh = nil
        break loop
      }
      n, err := w.Write(buf)
      if err != nil {
        return err
      }
      written += n
    case <-abortCh:
      return written, nil
    }
  }
  return written, nil
}
```

Note that I've not tested that code and there might be something wrong in that.

**Comment by hajimehoshi** [comment]
Hmm, that code has a bug: `writtenBytes` is not accurate when aborting. I don't think it is not hard to fix though.

**Comment by hajimehoshi** [comment]
> I would like to create a mechanism like jukebox using this technique and incorporate it into my game using ebiten.

Sorry I missed this comment. If you are using Ebiten, you can use `Player`'s `Pause`. http://godoc.org/github.com/hajimehoshi/ebiten/audio#Player.Pause Doesn't this work?

**Comment by KemoKemo** [comment]
Hi hajime-hoshi-san!

I understood that the Copy function should be able to Abort. Thank you so much for the code of AbortableCopy! And now, I am convinced that ebiten's Player is the best choice for me.
I'm sorry to have disturbed you....

I'll try to implement the jukebox in my ebiten game!

**Comment by hajimehoshi** [comment]
No problem. Thank you for using Oto and Ebiten!

**Pull request closed without merging**
