### PR TITLE
ignore unclosed players

### PR DESCRIPTION
**Pull request by DianeLooney**

### CODE REVIEW

**Comment by DianeLooney** [comment]
Not ready for review yet, but going to open this now so I don't forget about it.

**Comment by DianeLooney** [comment]
Fixing this won't happen soon, as I'm focused on other projects atm. Going to close this so there's not clutter hanging around in the repo.

**Comment by hajimehoshi** [comment]
Acknowledged. Please take your time.

**Comment by hajimehoshi** [comment]
Thank you for tackling the issue!

**Pull request closed without merging**
